---
title: CivicTechGbg
timezone: Europe/Stockholm
collections:
  hackathons:
    title: Hackathons
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: posts
  values:
    layout: project
    lang: sv
- scope:
    path: ''
    type: hackathons
  values:
    layout: project
    lang: sv
    event-date: 
    event-date-desc: 
    place: 
    ref: 
    links:
    - title: 
      url: 
      style: 
    image-top: 
    excerpt: 
    ingress-text: 
    projects:
    - title: 
      text: 
      image: 
      links:
      - title: 
        url: 
    partner-text: 
    partner-links:
    - name: 
      logo: 
      link: 
permalink: "/projects/:title/"
description: Hackathons för Göteborgs Civic Tech-community
theme: jekyll-theme-cayman
plugins:
- jemoji
project-title:
  sv: Kommande hackathons
  en: Hackathons
projects:
  sv: Projekt
  en: Projects
contact:
  sv:
    title: Vill du vara med?
    text: Det här är ett första utkast till ett samarbete och gemensamma event. Kontakta
      gärna oss om din organisation vill vara med, eller om du har idéer och förslag.
  en:
    title: Join us!
    text: This is the first draft for a cooperation to a common event. Please, contact
      us if you'd like your organisation to participate, or if you have any ideas
      and suggestions!
partner:
  sv:
    initiative: Ett initiativ från
    partnership: I samarbete med
  en:
    initiative: An initiative from
    partnership: In partnership with
projectmanager:
  sv: Projektledare
  en: Project manager
projectpartner:
  sv: Projektpartner
  en: Project partner
partners:
- title: Göteborgs Stad - Förvaltningen för konsument- och medborgarservice
  logo: "/uploads/logo-goteborg.png"
  link: http://goteborg.se/wps/portal/start/kommun-o-politik/kommunens-organisation/forvaltningar/forvaltningar/forvaltningen-for-konsument--och-medborgarservice-/!ut/p/z1/hU7NCoMwGHsar_1q_Wm7WxlD0P3ALrpehrpOZauVWjfY00-Pg40FcghJSEBCAbIvH11Tus705X3WJxmfQ5JgPw39LNkIikW0JtFufwiyI4H8X0DONv4BgSEF2VUaPWuNMCIkoowwzhkNGY85XfZFXwWsAWnVVVll0WTnW61zw7jysIcvU31b2BhUG-3hb5XWjA6KzyQMunhtVS7e-Y0waA!!/dz/d5/L2dBISEvZ0FBIS9nQSEh/
- title: Solidariskt Kylskåp
  logo: "/uploads/logo-solikyl.jpg"
  link: http://solikyl.se/
- title: Gothenburg Hackerspace
  logo: "/uploads/logo-gbghackerspace.jpg"
  link: https://www.facebook.com/gbghackerspace
