---
title: CivicTechSweden
timezone: Europe/Stockholm
collections:
  hackathons:
    title: Hackathons
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  groups:
    title: Groups
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: groups
  values:
    layout: project
    lang: sv
- scope:
    path: ''
    type: posts
  values:
    layout: project
    lang: sv
    ref:
    excerpt:
    ingress-text:
    image:
    links:
    - title:
      url:
    contact:
    - name:
      image:
      text:
      mail:
      organisation:
      organisation-link:
- scope:
    path: ''
    type: hackathons
  values:
    layout: project
    lang: sv
    ref:
    image:
    excerpt:
    ingress-text:
    event-date:
    event-date-desc:
    place:
    links:
    - title:
      url:
      style:
permalink: "/projects/:title/"
description: Hackathons för Sveriges Civic Tech-community
theme: jekyll-theme-cayman
plugins:
- jemoji
project-title:
  sv: Hackathon
  en: Hackathons
projects:
  sv: Projekt
  en: Projects
join:
  sv: Kom med i diskussionen
  en: Join the discussion
register:
  sv: Anmälan för deltagare
  en: Register participation
register_desc:
  sv: Anmäl dig här för att vara med på hackathonet
  en: Register here to participate in the hackathon
contact:
  sv:
    title: Vill du vara med?
    text: CivicTechSweden är ett samarbete mellan organisationer, nätverk och offentliga
      aktörer. Kontakta gärna oss om din organisation vill vara med som arrangör!
  en:
    title: Join us!
    text: CivicTechSweden is a cooperation between organisations, networks and the
      public sector. Please get in touch if you want to be a part of the network!
partner:
  sv:
    initiative: Ett initiativ från
    partnership: I samarbete med
    support: Med stöd av
  en:
    initiative: An initiative from
    partnership: In partnership with
    support: Supported by
projectmanager:
  sv: Projektledare
  en: Project manager
projectpartner:
  sv: Projektpartner
  en: Project partner
partners:
- title: Digidem Lab
  link: http://digidemlab.org
  logo: "/uploads/logo-digidemlab.png"
- title: Allmänna Arvsfonden
  link: http://arvsfonden.se
  logo: "/uploads/logo-arvsfonden.png"
- title: Göteborgs Stad - Förvaltningen för konsument- och medborgarservice
  logo: "/uploads/logo-goteborg.png"
  link: http://goteborg.se/wps/portal/start/kommun-o-politik/kommunens-organisation/forvaltningar/forvaltningar/forvaltningen-for-konsument--och-medborgarservice-/!ut/p/z1/hU7NCoMwGHsar_1q_Wm7WxlD0P3ALrpehrpOZauVWjfY00-Pg40FcghJSEBCAbIvH11Tus705X3WJxmfQ5JgPw39LNkIikW0JtFufwiyI4H8X0DONv4BgSEF2VUaPWuNMCIkoowwzhkNGY85XfZFXwWsAWnVVVll0WTnW61zw7jysIcvU31b2BhUG-3hb5XWjA6KzyQMunhtVS7e-Y0waA!!/dz/d5/L2dBISEvZ0FBIS9nQSEh/
- title: Solidariskt Kylskåp
  logo: "/uploads/logo-solikyl.jpg"
  link: http://solikyl.se/
- title: Gothenburg Hackerspace
  logo: "/uploads/logo-gbghackerspace.jpg"
  link: https://www.facebook.com/gbghackerspace
- title: Göteborgsregionens Kommunalförbund
  logo: "/uploads/gr_color_ny_stor.png"
  link: http://www.grkom.se/toppmenyn/dettajobbargrmed/miljoochsamhallsbyggnad/miljoochkretslopp.4.4fea3bce111092982468000586.html
- title: 'ABF '
  logo: "/uploads/ABF_logo_w.svg.png"
  link: http://www.abf.se
- title: Sharing cities Sweden
  logo: "/uploads/LOGO%20SCS_horizontal%20w%20text%20(1500%20px).png"
  link: https://www.sharingcities.se/
- title: Skjutsgruppen
  logo: "/uploads/Sjutsgruppen_JPG.jpg"
  link: https://skjutsgruppen.nu/
