---
title: CivicTechGbg
timezone: Europe/Stockholm
collections:
  hackathons:
    title: Hackathons
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: posts
  values:
    layout: project
    lang: sv
    ref: 
    excerpt: 
    ingress-text: 
    image: 
    links:
    - title: 
      url: 
    contact:
    - name: 
      image: 
      text: 
      mail: 
      organisation: 
      organisation-link: 
- scope:
    path: ''
    type: hackathons
  values:
    layout: project
    lang: sv
    ref: 
    image: 
    excerpt: 
    ingress-text: 
    event-date: 
    event-date-desc: 
    place: 
    links:
    - title: 
      url: 
      style: 
permalink: "/projects/:title/"
description: Hackathons för Göteborgs Civic Tech-community
theme: jekyll-theme-cayman
plugins:
- jemoji
project-title:
  sv: Tidigare hackathons
  en: Hackathons
projects:
  sv: Projekt
  en: Projects
contact:
  sv:
    title: Vill du vara med?
    text: CivicTechGbg är ett samarbete mellan organisationer, nätverk och offentliga aktörer. Kontakta
      gärna oss om din organisation vill vara med som arrangör!
  en:
    title: Join us!
    text: CivicTechGbg is a cooperation between organisations, networks and the public sector. Please get in touch if you want to be a part of the network!
partner:
  sv:
    initiative: Ett initiativ från
    partnership: I samarbete med
  en:
    initiative: An initiative from
    partnership: In partnership with
projectmanager:
  sv: Projektledare
  en: Project manager
projectpartner:
  sv: Projektpartner
  en: Project partner
partners:
- title: Göteborgs Stad - Förvaltningen för konsument- och medborgarservice
  logo: "/uploads/logo-goteborg.png"
  link: http://goteborg.se/wps/portal/start/kommun-o-politik/kommunens-organisation/forvaltningar/forvaltningar/forvaltningen-for-konsument--och-medborgarservice-/!ut/p/z1/hU7NCoMwGHsar_1q_Wm7WxlD0P3ALrpehrpOZauVWjfY00-Pg40FcghJSEBCAbIvH11Tus705X3WJxmfQ5JgPw39LNkIikW0JtFufwiyI4H8X0DONv4BgSEF2VUaPWuNMCIkoowwzhkNGY85XfZFXwWsAWnVVVll0WTnW61zw7jysIcvU31b2BhUG-3hb5XWjA6KzyQMunhtVS7e-Y0waA!!/dz/d5/L2dBISEvZ0FBIS9nQSEh/
- title: Solidariskt Kylskåp
  logo: "/uploads/logo-solikyl.jpg"
  link: http://solikyl.se/
- title: Gothenburg Hackerspace
  logo: "/uploads/logo-gbghackerspace.jpg"
  link: https://www.facebook.com/gbghackerspace
- title: Göteborgsregionens Kommunalförbund
  logo: "/uploads/gr_color_ny_stor.png"
  link: http://www.grkom.se/toppmenyn/dettajobbargrmed/miljoochsamhallsbyggnad/miljoochkretslopp.4.4fea3bce111092982468000586.html
- title: Räkna till 10
  logo: "/uploads/RT10_logo_neg.jpg"
  link: http://raknatill10.se/
- title: 'ABF '
  logo: "/uploads/ABF_logo_w.svg.png"
  link: http://www.abf.se
