---
title: CivicTechGbg
timezone: Europe/Stockholm
collections:
  hackathons:
    title: Hackathons
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: hackathons
  values:
    layout: project
    lang: sv
    event-date:
    event-date-desc: # datum som text, tex 28 februari 2018
    place: # stad och plats
    ref: # används för översättning
    links: # Anmälan osv
    - title:
      url:
      style:
    image-top: # Bild under ingressen
    excerpt: # Kort sammandrag
    ingress-text:
    projects:
    - title:
      text:
      image:
      links:
      - title:
        url:
    partner-text:
    partner-links:
    - name:
      logo:
      link:
description: Hackathons för Civic Tech-communitiet i Göteborg
theme: jekyll-theme-cayman
plugins:
- jemoji
project-title:
  sv: Kommande hackathons
  en: Hackathons
projects:
  sv: Projekt
  en: Projects
contact:
  sv:
    title: Vill du vara med?
    text: Det här är ett första utkast till ett samarbete och gemensamma event. Kontakta
      gärna oss om din organisation vill vara med, eller om du har idéer och förslag.
  en:
    title: Join us!
    text: This is the first draft for a cooperation to a common event. Please, contact
      us if you'd like your organisation to participate, or if you have any ideas
      and suggestions!
partner:
  sv:
    initiative: Ett initiativ från
    partnership: I samarbete med
  en:
    initiative: An initiative from
    partnership: In partnership with
partners:
- title: Solidariskt Kylskåp
  logo: "/uploads/logo-solikyl.jpg"
  link: http://solikyl.se/
